# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- script: |
    jf rt ping
    jf mvnc --repo-resolve-releases=dro-backend-maven-virtual \
            --repo-deploy-releases=dro-backend-maven-virtual \
            --repo-resolve-snapshots=dro-backend-maven-virtual \
            --repo-deploy-snapshots=dro-backend-maven-virtual
    
  displayName: 'Artifactory config'

