# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  vmImage: ubuntu-latest

steps:
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'Soleng Saas CLI'
    command: |
      jf rt ping
      jf rt bce $(Build.DefinitionName) $(Build.BuildNumber)
      jf mvnc --repo-resolve-releases=dro-backend-maven-virtual --repo-deploy-releases=dro-backend-maven-virtual --repo-resolve-snapshots=dro-backend-maven-virtual --repo-deploy-snapshots=dro-backend-maven-virtual
      jf mvn --build-name=$(Build.DefinitionName) -Drevision=1.$(Build.BuildId).0 --build-number=$(Build.BuildNumber) -Dmaven.test.skip=true clean package deploy
      jf rt bp $(Build.DefinitionName) $(Build.BuildNumber) --build-url=https://dev.azure.com/davidro0580/DevopsDemo/_build/results?buildId=$(Build.BuildId)
      jf audit --mvn
  env: 
    JFROG_CLI_BUILD_PROJECT: dro
  displayName: 'Artifactory config'
